#!/usr/bin/env node

/**
 * Configuration Builder Script
 * 
 * This script processes the config.json file, substitutes environment variables,
 * validates the configuration against the schema, and generates a JavaScript
 * module that can be loaded by the frontend application.
 */

const fs = require('fs');
const path = require('path');
const Ajv = require('ajv');

// Load environment variables from .env.local if it exists
require('dotenv').config({ path: path.join(__dirname, '.env.local') });

// Configuration paths
const CONFIG_PATH = path.join(__dirname, 'config.json');
const SCHEMA_PATH = path.join(__dirname, 'config.schema.json');
const OUTPUT_PATH = path.join(__dirname, 'src', 'config.generated.js');

/**
 * Substitute environment variables in a string
 * Replaces ${VAR_NAME} with the value from process.env.VAR_NAME
 */
function substituteEnvVar(value) {
  if (typeof value !== 'string') {
    return value;
  }
  
  // Match ${VAR_NAME} pattern
  const pattern = /\$\{([^}]+)\}/g;
  return value.replace(pattern, (match, varName) => {
    const envValue = process.env[varName];
    if (envValue === undefined) {
      throw new Error(`Environment variable ${varName} is not defined`);
    }
    return envValue;
  });
}

/**
 * Recursively substitute environment variables in configuration object
 */
function substituteEnvVars(config) {
  if (Array.isArray(config)) {
    return config.map(item => substituteEnvVars(item));
  }
  
  if (config !== null && typeof config === 'object') {
    const result = {};
    for (const [key, value] of Object.entries(config)) {
      result[key] = substituteEnvVars(value);
    }
    return result;
  }
  
  return substituteEnvVar(config);
}

/**
 * Validate configuration against JSON schema
 */
function validateConfig(config, schema) {
  const ajv = new Ajv({ allErrors: true });
  const validate = ajv.compile(schema);
  const valid = validate(config);
  
  if (!valid) {
    const errors = validate.errors.map(err => ({
      path: err.instancePath || err.dataPath || 'root',
      message: err.message,
      params: err.params
    }));
    return { valid: false, errors };
  }
  
  return { valid: true, errors: [] };
}

/**
 * Generate JavaScript module from configuration
 */
function generateConfigModule(config) {
  const configJson = JSON.stringify(config, null, 2);
  return `// This file is auto-generated by build-config.js
// DO NOT EDIT MANUALLY

window.APP_CONFIG = ${configJson};
`;
}

/**
 * Main build function
 */
function buildConfig() {
  console.log('Building configuration...');
  
  try {
    // Read config.json
    console.log(`Reading configuration from ${CONFIG_PATH}`);
    if (!fs.existsSync(CONFIG_PATH)) {
      throw new Error(`Configuration file not found: ${CONFIG_PATH}`);
    }
    
    const configContent = fs.readFileSync(CONFIG_PATH, 'utf8');
    let config;
    try {
      config = JSON.parse(configContent);
    } catch (err) {
      throw new Error(`Invalid JSON in config file: ${err.message}`);
    }
    
    // Substitute environment variables
    console.log('Substituting environment variables...');
    config = substituteEnvVars(config);
    
    // Read schema
    console.log(`Reading schema from ${SCHEMA_PATH}`);
    if (!fs.existsSync(SCHEMA_PATH)) {
      throw new Error(`Schema file not found: ${SCHEMA_PATH}`);
    }
    
    const schemaContent = fs.readFileSync(SCHEMA_PATH, 'utf8');
    const schema = JSON.parse(schemaContent);
    
    // Validate configuration
    console.log('Validating configuration...');
    const validation = validateConfig(config, schema);
    
    if (!validation.valid) {
      console.error('Configuration validation failed:');
      validation.errors.forEach(err => {
        console.error(`  - ${err.path}: ${err.message}`);
        if (err.params) {
          console.error(`    Details: ${JSON.stringify(err.params)}`);
        }
      });
      process.exit(1);
    }
    
    // Generate output
    console.log('Generating configuration module...');
    const output = generateConfigModule(config);
    
    // Ensure output directory exists
    const outputDir = path.dirname(OUTPUT_PATH);
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }
    
    // Write output file
    fs.writeFileSync(OUTPUT_PATH, output, 'utf8');
    console.log(`Configuration written to ${OUTPUT_PATH}`);
    console.log('Build complete!');
    
  } catch (err) {
    console.error('Build failed:', err.message);
    process.exit(1);
  }
}

// Run if called directly
if (require.main === module) {
  buildConfig();
}

module.exports = {
  substituteEnvVar,
  substituteEnvVars,
  validateConfig,
  generateConfigModule,
  buildConfig
};
